owner: ds-wizard
repo: status

sites:
  - name: ds-wizard.org
    url: https://ds-wizard.org
  - name: guide.ds-wizard.org
    url: https://guide.ds-wizard.org
  - name: ideas.ds-wizard.org
    url: https://ideas.ds-wizard.org
  - name: localize.ds-wizard.org
    url: https://localize.ds-wizard.org
  - name: changelog.ds-wizard.org
    url: https://changelog.ds-wizard.org

status-website:
  baseUrl: /status
  logoUrl: https://ds-wizard.github.io/status/dsw-icon.svg
  name: "Data Stewardship Wizard | Status"
  introTitle: "Status page for [**ds-wizard.org**](https://ds-wizard.org) services."
  introMessage: "This is status page monitors the availability of the Data Stewardship Wizard open-source project website(s) and related services. It also contains important information in case of outages, scheduled maintenance, and other incidents."
  themeUrl: https://ds-wizard.github.io/status/custom-theme.css
  navbar:
    - title: Status
      href: /status
    - title: Homepage
      href: https://ds-wizard.org

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
